name: iOS starter workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Select Xcode
        run: sudo Xcode-select -switch /Applications/Xcode.app
      - name: Select Xcode
        run: xcrun simctl list devices

      - name: Build & Test
        run: xcodebuild test -workspace testCIcd.xcodeproj/project.xcworkspace -scheme testCIcd -destination 'platform=iOS Simulator,id:66A312C7-612F-437F-B73D-10ED87D39F3A,name=iPhone 13 Pro Max,OS=16.2'
