name: iOS starter workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Select Xcode
        run: sudo Xcode-select -switch /Applications/Xcode_13.2.1.app
      - name: Build & Test
        run: xcodebuild clean build test -workspace testCIcd/project.xcworkspace -scheme testCIcd -destination 'platform=iOS Simulator,name=iPhone 12 Pro,OS=15.2'
